from __future__ import annotations

from dataclasses import dataclass

from .models import LyricsDocument
from .timecode import ass_clock


@dataclass(frozen=True)
class AssStyle:
    font: str = "Microsoft YaHei"
    font_size: int = 58
    text_color: str = "#FFFFFF"
    highlight_color: str = "#FFD54A"
    outline_color: str = "#111111"
    outline: float = 3.0
    shadow: float = 1.2
    margin_v: int = 72
    resolution: tuple[int, int] = (1920, 1080)


def _ass_color(value: str, alpha: int = 0) -> str:
    value = value.strip().lstrip("#")
    if len(value) == 3:
        value = "".join(char * 2 for char in value)
    if len(value) != 6:
        raise ValueError(f"Expected an RGB hex color, got: {value!r}")
    red, green, blue = value[0:2], value[2:4], value[4:6]
    return f"&H{alpha:02X}{blue}{green}{red}".upper()


def _escape_ass_text(value: str) -> str:
    return value.replace("\\", r"\\").replace("{", r"\{").replace("}", r"\}").replace("\n", r"\N")


def write_ass(document: LyricsDocument, style: AssStyle | None = None) -> str:
    document.require_timed()
    style = style or AssStyle()
    width, height = style.resolution
    primary = _ass_color(style.highlight_color)
    secondary = _ass_color(style.text_color)
    outline = _ass_color(style.outline_color)

    header = f"""[Script Info]
; Generated by Karaoke Forge
ScriptType: v4.00+
PlayResX: {width}
PlayResY: {height}
ScaledBorderAndShadow: yes
WrapStyle: 2

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Karaoke,{style.font},{style.font_size},{primary},{secondary},{outline},&H80000000,-1,0,0,0,100,100,0,0,1,{style.outline},{style.shadow},2,60,60,{style.margin_v},1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""
    events: list[str] = []
    for line in document.lines:
        assert line.start is not None and line.end is not None
        if line.tokens:
            karaoke_parts: list[str] = []
            for token in line.tokens:
                duration = max(1, round((token.end - token.start) * 100))
                karaoke_parts.append(r"{\kf" + str(duration) + "}" + _escape_ass_text(token.text))
            lyric_text = "".join(karaoke_parts)
        else:
            lyric_text = _escape_ass_text(line.text)
        events.append(
            "Dialogue: 0,"
            f"{ass_clock(line.start)},{ass_clock(line.end)},"
            f"Karaoke,,0,0,0,,{{\\fad(120,180)}}{lyric_text}"
        )
    return header + "\n".join(events) + "\n"
